baseURL = "https://seste.rs/"
languageCode = "en-us"
title = "Sesters"
theme = "landing-page-hugo"
[params]
	description = "Fast, offline command-line currency converter"

[[params.social]]
	title = "github"
	icon = "github"
	url = "https://github.com/leowzukw/sesters"